name: ML_CI_Pipeline

on:
  push:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - run: python train.py

      - uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: model.pkl

      - uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: metrics.json

  report:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: model-artifacts

      - run: echo Run completed by: YELETI KALYAN BABU - 22bcs110